[mypy]
python_version = 3.12
strict = True

[mypy-mu_3sl_interface]
ignore_missing_imports = True

[mypy-mu_3sl_interface.*]
ignore_missing_imports = True

[mypy-mu_3sl_calibration_adjustments]
ignore_missing_imports = True

[mypy-mu_3sl_calibration_adjustments.*]
ignore_missing_imports = True

[mypy-ingeniamotion]
ignore_missing_imports = True

[mypy-ingeniamotion.*]
ignore_missing_imports = True

[mypy-matplotlib]
ignore_missing_imports = True

[mypy-matplotlib.*]
ignore_missing_imports = True

[mypy-numpy]
ignore_missing_imports = True

[mypy-numpy.*]
ignore_missing_imports = True